### ISSUE TITLE
Talk about the forum somewhere

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/projetpp.github.io#26]

**Comment by Ezibenroc** [comment]
We should add a clickable logo on bottom right. An idea of logo?
@ProgVal: is there an official logo we should use for this forum platform?

**Comment by ProgVal** [comment]
No.

Maybe we could use a derivative of the Platypus' logo, with another color?

**Comment by yhamoudi** [comment]
What about:
![image](https://cloud.githubusercontent.com/assets/6659728/6318929/85970034-baa9-11e4-86af-2e5b28c6c766.png)

(from https://github.com/google/material-design-icons/blob/master/communication/svg/design/ic_forum_48px.svg, still used for the icons at the bottom of the website)

**Comment by Ezibenroc** [comment]
I prefer the idea of @yhamoudi.

Any other suggestion?

**Comment by ProgVal** [comment]
The license of this icon is CC-BY, so we have to write somewhere where it comes from. I would prefer one in the public domain.

**Comment by Ezibenroc** [comment]
We already use icons from this repository (the email icon).
And we have this in footer: `© 2015 PPP with help from Jekyll Bootstrap, Twitter Bootstrap and Material Design Icons`.

**Comment by yhamoudi** [comment]
> The license of this icon is CC-BY, so we have to write somewhere where it comes from. I would prefer one in the public domain.

It's already done at the bottom of the website (since the other icons come from the same source)

**Comment by yhamoudi** [comment]
We could also provide a link to the forum on the [about page](http://projetpp.github.io/about.html)

**Comment by Ezibenroc** [comment]
> We could also provide a link to the forum on the about page

Yes we should do both.

**Comment by ProgVal** [comment]
oh, ok, then

**Comment by Ezibenroc** [comment]
Pull request: https://github.com/ProjetPP/projetpp.github.io/pull/27
